name: ASSN4 CI

on:
  push:
    branches: [ "main" ]
    paths: 
        - assn4/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd assn4 && make
