name: ASSN1 CI

on:
  push:
    branches: [ "main" ]
    paths: 
        - assn1/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd assn1 && make
