name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with: 
        version: '6.0.0'
    - uses: actions/checkout@v3
    - name: build
      run: |
        cmake -S . -B build
        cd build
        make -j
