name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services: 
      registry: 
        image: registry:2
        ports: 
          - 5000:5000
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with: 
        driver-opts: network=host
    - name: Docker Build
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: localhost:5000/assn-ci:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Check Build Success
      uses: addnab/docker-run-action@v3
      with: 
        image: localhost:5000/assn-ci:latest
        run: test .successful && echo "BUILD DONE SUCCESSFULLY"
    - name: Test
      uses: addnab/docker-run-action@v3
      with: 
        image: localhost:5000/assn-ci:latest
        run: ctest
