name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Image Build
      run: docker buildx build --platform linux/amd64 -t assn-ci:github --cache-to type=gha --cache-from type=gha --push .
    - name: Check Build Success
      run: docker run --rm assn-ci:github test .successful && echo "BUILD DONE SUCCESSFULLY"
    - name: Test
      run: docker run --rm assn-ci:github ctest
