name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Build
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./Dockerfile
        load: true
        tags: assn-ci:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Show Image List on Docker
      run: docker image ls
    - name: Check Build Success
      run: docker run --rm assn-ci:latest test .successful && echo "BUILD DONE SUCCESSFULLY"
    - name: Test
      run: docker run --rm assn-ci:latest ctest
