name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Build
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./Dockerfile
        push: false
        tags: assn-ci:latest
    - name: Check Build Success
      uses: addnab/docker-run-action@v3
      with: 
        image: assn-ci:latest
        run: test .successful && echo "BUILD DONE SUCCESSFULLY"
    - name: Test
      uses: addnab/docker-run-action@v3
      with: 
        image: assn-ci:latest
        run: ctest
